Repository lonestarvirtual/skyOS, pull requests merged in 2020-05, with the labels that each got.

#23 introduction of github actions
  .github/workflows/publish.yml
  .github/workflows/verify.yml
  README.md
  config/database.yml
  docker-compose.yml.example
Labels: enhancement

#28 updated audited table columns to support uuid
  db/migrate/20200510034140_fix_audited.rb
  db/schema.rb
Labels: bug

#29 updated specs to current state and generic cleanup
  .github/workflows/verify.yml
  app/controllers/contacts_controller.rb
  app/policies/airline_policy.rb
  app/policies/airport_policy.rb
  app/policies/equipment_policy.rb
  app/policies/fleet_policy.rb
  app/policies/flight_policy.rb
  app/policies/pilot_policy.rb
  app/policies/simulator_policy.rb
  spec/factories/airlines.rb
  spec/factories/airports.rb
  spec/factories/contacts.rb
  spec/factories/equipment.rb
  spec/factories/fleets.rb
  spec/factories/flights.rb
  spec/factories/networks.rb
  spec/factories/pilots.rb
  spec/factories/pireps.rb
  spec/factories/simulators.rb
  spec/models/network_spec.rb
  spec/models/pirep_spec.rb
  spec/models/pirep_status_spec.rb
  spec/policies/airport_policy_spec.rb
  spec/policies/application_policy_spec.rb
  spec/policies/equipment_policy_spec.rb
  spec/policies/fleet_policy_spec.rb
  spec/policies/flight_policy_spec.rb
  spec/policies/network_policy_spec.rb
  spec/policies/pilot_policy_spec.rb
  spec/policies/pirep_policy_spec.rb
  spec/policies/simulator_policy_spec.rb
  spec/requests/admin/airlines_request_spec.rb
  spec/requests/admin/airports_request_spec.rb
  spec/requests/admin/equipment_request_spec.rb
  spec/requests/admin/fleets_request_spec.rb
  spec/requests/admin/flights_request_spec.rb
  spec/requests/admin/networks_request_spec.rb
  spec/requests/admin/pilots_request_spec.rb
  spec/requests/admin/pireps_request_spec.rb
  spec/requests/admin/simulators_request_spec.rb
  spec/requests/api/v1/airports_request_spec.rb
  spec/requests/contacts_request_spec.rb
  spec/requests/fleet_request_spec.rb
  spec/requests/flights_request_spec.rb
  spec/requests/home_request_spec.rb
  spec/requests/logbooks_request_spec.rb
  spec/requests/pilots_request_spec.rb
  spec/requests/pireps_request_spec.rb
  spec/requests/policy_request_spec.rb
  spec/requests/profiles_request_spec.rb
  spec/support/controller_macros.rb
  spec/support/devise.rb
Labels: enhancement

#30 added admin page for site settings
  README.md
  app/assets/stylesheets/admin/settings.scss
  app/controllers/admin/settings_controller.rb
  app/helpers/admin/settings_helper.rb
  app/helpers/application_helper.rb
  app/models/pilot.rb
  app/models/setting.rb
  app/policies/setting_policy.rb
  app/views/admin/settings/_form.html.haml
  app/views/admin/settings/index.html.haml
  app/views/layouts/_footer.html.haml
  app/views/layouts/_head.html.haml
  app/views/layouts/menu/_admin.html.haml
  config/routes.rb
  db/seeds.rb
  spec/helpers/admin/settings_helper_spec.rb
  spec/policies/setting_policy_spec.rb
  spec/requests/admin/settings_request_spec.rb
Labels: enhancement

#32 added leaflet to webpack for mapping
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/destinations.scss
  app/assets/stylesheets/pireps.scss
  app/controllers/destinations_controller.rb
  app/helpers/destinations_helper.rb
  app/javascript/packs/application.js
  app/javascript/packs/controllers/maps_controller.js
  app/models/airport.rb
  app/views/destinations/index.html.haml
  app/views/layouts/_menu.html.haml
  app/views/pireps/_map.html.haml
  app/views/pireps/show.html.haml
  config/routes.rb
  package.json
  spec/factories/flights.rb
  spec/helpers/destinations_helper_spec.rb
  spec/models/airport_spec.rb
  spec/requests/destinations_request_spec.rb
  yarn.lock
Labels: enhancement

#36 Updates to the landing page
  app/assets/stylesheets/home.scss
  app/helpers/home_helper.rb
  app/models/setting.rb
  app/policies/setting_policy.rb
  app/views/admin/settings/_form.html.haml
  app/views/home/_newest_pilots.html.haml
  app/views/home/_statistics.html.haml
  app/views/home/index.html.haml
  app/views/layouts/_footer.html.haml
  spec/helpers/home_helper_spec.rb
Labels: enhancement

#38 bootstrap upgraded to 4.5
  package.json
  yarn.lock
Labels: enhancement

#39 Updated Docker entrypoint
  .rubocop.yml
  Dockerfile
  README.md
  app/models/permission.rb
  bin/docker-entrypoint.sh
  db/migrate/20200513142124_add_index_to_permission.rb
  db/schema.rb
  db/seeds.rb
  lib/tasks/skyos.rake
  lib/tasks/skyos/create_admin.rb
  lib/tasks/skyos/init_defaults.rb
  lib/tasks/skyos/install.rb
  lib/tasks/skyos/load_airports.rb
  spec/spec_helper.rb
Labels: enhancement

#45 Resolves #43 Refactored kaminari to not require third-party theme
  Gemfile
  Gemfile.lock
  app/views/admin/airlines/index.html.haml
  app/views/admin/airports/index.html.haml
  app/views/admin/announcements/index.html.haml
  app/views/admin/equipment/index.html.haml
  app/views/admin/fleets/index.html.haml
  app/views/admin/flights/index.html.haml
  app/views/admin/networks/index.html.haml
  app/views/admin/pilots/index.html.haml
  app/views/admin/pireps/index.html.haml
  app/views/admin/simulators/index.html.haml
  app/views/fleet/index.html.haml
  app/views/flights/index.html.haml
  app/views/kaminari/_first_page.html.haml
  app/views/kaminari/_gap.html.haml
  app/views/kaminari/_last_page.html.haml
  app/views/kaminari/_next_page.html.haml
  app/views/kaminari/_page.html.haml
  app/views/kaminari/_paginator.html.haml
  app/views/kaminari/_prev_page.html.haml
  app/views/logbooks/show.html.haml
  app/views/pilots/index.html.haml
Labels: enhancement

#49 Add drop down select download to fleet page
  app/controllers/fleet_controller.rb
  app/models/repaint.rb
  app/views/fleet/_aircraft.html.haml
  config/routes.rb
Labels: enhancement

#51 Switch to Paper Trail
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/helpers/pireps_helper.rb
  app/models/pirep.rb
  config/initializers/audited.rb
  config/initializers/paper_trail.rb
  db/migrate/20200502012248_install_audited.rb
  db/migrate/20200510034140_fix_audited.rb
  db/migrate/20200516123046_uninstall_audited.rb
  db/migrate/20200516140120_create_versions.rb
  db/migrate/20200516140121_add_object_changes_to_versions.rb
  db/schema.rb
Labels: dependencies, enhancement

#53 Resolves #50 added group_id to permitted parameters
  app/policies/pilot_policy.rb
  app/views/admin/pilots/_form.html.haml
  db/schema.rb
Labels: bug

#56 Add Upgrading instructions to README
  README.md
Labels: documentation

#59 Is logged in check on Homepage
  app/views/home/index.html.haml
Labels: enhancement

#62 Resolves #61 the recaptcha minimum score should always be a float
  app/controllers/contacts_controller.rb
  app/controllers/registrations_controller.rb
Labels: bug

#69 Websocket Notifications and Background Jobs
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/assets/sounds/ding.ogg
  app/assets/sounds/notification.ogg
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/notifications.scss
  app/channels/application_cable/connection.rb
  app/channels/notifications_channel.rb
  app/channels/pireps_channel.rb
  app/controllers/notifications_controller.rb
  app/helpers/notifications_helper.rb
  app/javascript/channels/notifications_channel.js
  app/javascript/channels/pireps_channel.js
  app/javascript/packs/controllers/notifications_controller.js
  app/javascript/stylesheets/_boostrap_custom.scss
  app/jobs/notification_broadcast_job.rb
  app/jobs/pirep_broadcast_job.rb
  app/models/notification.rb
  app/models/pilot.rb
  app/models/pirep.rb
  app/policies/notification_policy.rb
  app/policies/pirep_policy.rb
  app/views/layouts/_head.html.haml
  app/views/layouts/_menu.html.haml
  app/views/layouts/menu/_notifications.html.haml
  app/views/layouts/menu/_pilot.html.haml
  app/views/notifications/_dropdown.html.haml
  app/views/notifications/_notification.html.haml
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/routes.rb
  db/migrate/20200421142035_create_airports.rb
  db/migrate/20200514042636_create_announcements.rb
  db/migrate/20200516053452_create_notifications.rb
  db/migrate/20200522163631_notification_update.rb
  db/schema.rb
  docker-compose.yml
  docker-compose.yml.example
  spec/channels/notifications_channel_spec.rb
  spec/channels/pireps_channel_spec.rb
  spec/factories/notifications.rb
  spec/helpers/notifications_helper_spec.rb
  spec/jobs/notification_broadcast_job_spec.rb
  spec/jobs/pirep_broadcast_job_spec.rb
  spec/models/notification_spec.rb
  spec/models/pilot_spec.rb
  spec/models/pirep_spec.rb
  spec/policies/notification_policy_spec.rb
  spec/requests/notifications_request_spec.rb
Labels: enhancement

#71 Added support for Heroku deployments
  Procfile
  README.md
  config/database.yml
  docker-compose.yml
  docker-compose.yml.example
Labels: enhancement

#73 Resolves #72 Added pilot notification when a PIREP is approved
  .rubocop.yml
  app/models/pirep.rb
  spec/models/pirep_spec.rb
Labels: enhancement

#74 restored missing PIREP held status
  db/seeds.rb
Labels: bug
